<div id="tennis-bracket-front-<?php echo $tennis_bracket_id ?>"></div>
<script type="text/javascript">
    jQuery( document ).ready( function( $ ) {
        var tennisBracketData<?php echo $tennis_bracket_id ?> = JSON.parse( '<?php echo $tennis_bracket_data; ?>' );

        $( '#tennis-bracket-front-<?php echo $tennis_bracket_id ?>' ).bracket({
            init: tennisBracketData<?php echo $tennis_bracket_id ?>,
        });
    });
</script>